version: '3.8'

services:
  api:
    build: .
    container_name: housing_api
    command: ["sh", "start_api.sh"]
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"


  frontend:
    build: .
    container_name: housing_frontend
    command: streamlit run app/main.py --server.port=8501 --server.address=0.0.0.0
    volumes:
      - .:/workspace
    ports:
      - "8501:8501"
    depends_on:
      - api